# Use uma imagem base do Node.js
FROM node:18-alpine

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /usr/src/app

# Copie o arquivo package.json e package-lock.json para o diretório de trabalho
COPY package*.json ./

# Instale as dependências
RUN npm install

RUN npm install class-transformer
RUN npx prisma generate

# Copie todo o código da aplicação para o diretório de trabalho
COPY . .

# Compile o código TypeScript para JavaScript
RUN npm run build

# Exponha a porta definida no .env ou a porta padrão 3333
EXPOSE ${PORT:-3333}

# Comando para iniciar a aplicação
CMD ["npm", "run", "start:prod"]