# Use uma imagem base do Node.js
FROM node:18-alpine

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /usr/src/app

# Copie os arquivos de dependências
COPY package*.json ./

# Copie a pasta do Prisma para que o schema seja encontrado
COPY prisma ./prisma

# Instale as dependências
RUN npm install

# Caso o class-transformer não esteja no package.json, instale-o
RUN npm install class-transformer

# Gere o Prisma Client (agora o schema.prisma já está disponível)
RUN npx prisma generate

# Copie o restante do código da aplicação
COPY . .

# Compile o código TypeScript para JavaScript
RUN npm run build

# Exponha a porta definida no .env ou a porta padrão 3333
EXPOSE ${PORT:-3333}

# Comando para iniciar a aplicação
CMD ["npm", "run", "start:prod"]
